User.create!(username: 'Alfie102', password: 'alexrocks', image_url: 'https://photos.app.goo.gl/eYtcE3SVjAP7mmpz9')
User.create!(username: 'MoxxieXOXO', password: 'alexiscool', image_url: 'https://photos.app.goo.gl/XGDznrrCenM1oBL28')
User.create!(username: 'AggieBaby', password: 'alexisfun', image_url: 'https://photos.app.goo.gl/SLL31jhm1eNNq82t6')
User.create!(username: 'MJ123', password: 'alexisgreat', image_url: 'https://photos.app.goo.gl/V8he9FLZGziwEPCcA')
User.create!(username: 'Alexu09', password: 'alexisme', image_url: 'https://photos.app.goo.gl/RogjecaBg5RvdpZq5')

Item.create!(name: 'Spoils Bag', image_url: 'https://photos.app.goo.gl/QSjTsyc9H1oeUxik8' , description: 'A bag to hold spoils dropped by felled enemies', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY4850 50")
Item.create!(name: 'Bait Bag', image_url: 'https://photos.app.goo.gl/tyTN63G41ZhMeBwv8' , description: 'A bag to hold bait', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 30")
Item.create!(name: 'Mail Bag', image_url: 'https://photos.app.goo.gl/N5apQuVFR2xEwd5u7' , description: 'A bag to hold mail', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 40")
Item.create!(name: 'Simple Flower', image_url: 'https://photos.app.goo.gl/SGGGLYqBRFfu7d3x5' , description: 'A simple flower to help beautify a town', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 10")
Item.create!(name: 'Pretty Flower', image_url: 'https://photos.app.goo.gl/4NVwykaXpVgGCVEF7' , description: 'A pretty flower to help beautify a town', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 20")
Item.create!(name: 'Exotic Flower', image_url: 'https://photos.app.goo.gl/nZGFeTGjDm6tzJLo8' , description: 'An exotic flower to help beautify a town', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 35")
Item.create!(name: 'Windmill', image_url: 'https://photos.app.goo.gl/qRQJ1cG7Ub7KiYYP8' , description: 'A cute decoration to add some flair to a town', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 15")
Item.create!(name: 'Bottle', image_url: 'https://photos.app.goo.gl/3bBUiaS5fzcNi9Gd8' , description: 'Used to hold stuff', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 50")
Item.create!(name: 'Green Potion', image_url: 'https://photos.app.goo.gl/s8vK8qdRGper2LEL9' , description: 'Replenishes magic', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 25")
Item.create!(name: 'Blue Potion ', image_url: 'https://photos.app.goo.gl/BciCxj5FXVti3mGS8' , description: 'Replenishes both health and magic', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 45")
Item.create!(name: "Gramma\'s Soup", image_url: 'https://photos.app.goo.gl/rGMDvjHnbDt2onCZA' , description: 'Yummy and replenishes heath, magic, and gives a boost', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 50")
Item.create!(name: 'Pear', image_url: 'https://photos.app.goo.gl/UN5vbgczu7VrMxh37' , description: 'Used to attract seagulls', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 15")
Item.create!(name: 'Telescope', image_url: 'https://photos.app.goo.gl/bQe5KbyFroyyzncy6' , description: 'Used to see far', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 60")
Item.create!(name: 'Treasure Map', image_url: 'https://photos.app.goo.gl/PpYwA74bRSAuvXaN6' , description: 'Location to some treasure', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 50")
Item.create!(name: 'A Piece of Triforce Treasure Map', image_url: 'https://photos.app.goo.gl/Fy1xrQeTPfVd7zv36' , description: 'Location to a piece of the triforce', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 150")
Item.create!(name: 'Stick', image_url: 'https://photos.app.goo.gl/cttMJLkDZ564Hggv9' , description: 'A stick', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 15")
Item.create!(name: 'Bomb', image_url: 'https://photos.app.goo.gl/yaoHLrtzyXoxmH219' , description: 'Blows stuff up', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 20")
Item.create!(name: 'Boomerang', image_url: 'https://photos.app.goo.gl/cdWxbj42iPrAysJ48' , description: 'Throw it and watch it come back', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 50")
Item.create!(name: 'Grappling Hook', image_url: 'https://photos.app.goo.gl/qRQJ1cG7Ub7KiYYP8' , description: 'Throw at enemies and ledges', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 75")
Item.create!(name: 'Bow', image_url: 'https://photos.app.goo.gl/rQupNq9LCJ2dQPx17' , description: 'A bow. Needs Arrows not included', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 100")
Item.create!(name: 'Bundle of Arrows', image_url: 'https://photos.app.goo.gl/uWbd4Ad7n6WtmgoPA' , description: 'Bundle of 10 arrows', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 25")
Item.create!(name: 'Hammer', image_url: 'https://photos.app.goo.gl/mCDdVoANCWP4qX2W9' , description: 'Great at hitting giant birds', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 200")
Item.create!(name: 'Iron Boots', image_url: 'https://photos.app.goo.gl/Q2XC9TsCi4jKJ6URA' , description: 'Makes you an immovable force', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 250")
Item.create!(name: 'Deku Leaf', image_url: 'https://photos.app.goo.gl/hXKH8162wh3VKsPT6' , description: 'Creates a powerful gust of wind', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 150")
Item.create!(name: "Hero\'s Sword", image_url: 'https://photos.app.goo.gl/P99GGpdi1ApPo49B9' , description: 'A sword that can seal darkness', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 450")
Item.create!(name: "Hero\'s Outfit", image_url: 'https://photos.app.goo.gl/vkU7K85ZfiU2PRYPA' , description: 'Said to have belonged to a hero from another time', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 200")
Item.create!(name: 'Piece of Heart', image_url: 'https://photos.app.goo.gl/FwMooKo6fKwr1HWH6' , description: 'Collect 4 to complete a Heart Container', price: "https://photos.app.goo.gl/ie99pUYwVtwLpvY48 150")

Review.create!(title: 'Great Purchase!', body: 'Holds all the goods I get from killing enemies',  user_id: 1, item_id: 1)
Review.create!(title: 'Nice', body: 'Perfect storage for my bait',  user_id: 2, item_id: 2)
Review.create!(title: 'Not Bad', body: "Does what it\'s supposed to",  user_id: 3, item_id: 3)
Review.create!(title: 'Okay', body: 'Nothing special, but adds a nice little flair',  user_id: 4, item_id: 4)
Review.create!(title: 'Pretty Nice', body: 'Looks really good',  user_id: 5, item_id: 5)
Review.create!(title: 'Beautiful!', body: 'Love the color and the design!',  user_id: 1, item_id: 6)
Review.create!(title: 'Cute', body: "It\'s a fun little touch to the area",  user_id: 2, item_id: 7)
Review.create!(title: 'Absoulte Necessity!', body: "Can\'t get far without this. Bought 4",  user_id: 3, item_id: 8)
Review.create!(title: 'Helpful', body: 'Nice to have on hand',  user_id: 4, item_id: 9)
Review.create!(title: 'Great Purchase!', body: 'Really great thing to have on hand',  user_id: 5, item_id: 10)
Review.create!(title: 'Tasty and Hearty', body: "Better than any potion I\'ve ever had",  user_id: 1, item_id: 11)
Review.create!(title: 'Not Bad', body: "It\'s alright; does what it needs to, but nothing special",  user_id: 2, item_id: 12)
Review.create!(title: 'Love This!', body: "Love it! I can\'t go anywhere without it",  user_id: 3, item_id: 13)
Review.create!(title: 'Not Easy to Use', body: "The directions aren\'t very clear, but it\'s better than nothing",  user_id: 4, item_id: 14)
Review.create!(title: 'Amazing!', body: 'It led me amazing treasure',  user_id: 5, item_id: 15)
Review.create!(title: 'Okay', body: 'Not bad for a cheap weapon',  user_id: 5, item_id: 16)
Review.create!(title: 'Necessary', body: "Always have some of these on me; they\'re always super useful",  user_id: 1, item_id: 17)
Review.create!(title: 'Difficult to Use', body: 'Pretty good weapon, but takes a lot of practice',  user_id: 2, item_id: 18)
Review.create!(title: 'So Much Fun!', body: 'I love that this has unlocked so many new places for me. AND, it can also be used as a weapon!',  user_id: 3, item_id: 19)
Review.create!(title: 'Good Buy', body: 'Great long-ranged weapon',  user_id: 4, item_id: 20)
Review.create!(title: 'Okay', body: 'Nothing special',  user_id: 5, item_id: 21)
Review.create!(title: 'Heavy but Strong', body: 'Very powerful, but super heavy',  user_id: 1, item_id: 22)
Review.create!(title: 'Great Purchase!', body: "Nothing can push me over when I\'m wearing these. Highly recommend",  user_id: 2, item_id: 23)
Review.create!(title: 'Suprisingly Useful!', body: "Doesn\'t seem like much, but it\'s incredibly handy",  user_id: 3, item_id: 24)
Review.create!(title: 'Legendary', body: "The only sword I\'ll ever need",  user_id: 4, item_id: 25)
Review.create!(title: 'Comfy', body: 'Super comfortable to move around in',  user_id: 5, item_id: 26)
Review.create!(title: 'Great', body: 'Getting 4 of these really made my life easier; wish I only needed one though',  user_id: 1, item_id: 27)




