User.create!(username: 'Alfie102', password: 'alexrocks', image_url: '/assets/regular dude icon.png')
User.create!(username: 'MoxxieXOXO', password: 'alexiscool', image_url: '/assets/blue hair chick icon.png')
User.create!(username: 'AggieBaby', password: 'alexisfun', image_url: '/assets/old man icon.png')
User.create!(username: 'MJ123', password: 'alexisgreat', image_url: '/assets/winky face icon.png')
User.create!(username: 'Alexu09', password: 'alexisme', image_url: '/assets/cool dude icon.png')

Item.create!(name: 'Spoils Bag', image_url: '/assets/spoils bag.png' , description: 'A bag to hold spoils dropped by felled enemies', price: "/assets/rupee.png 50")
Item.create!(name: 'Bait Bag', image_url: '/assets/bait bag .png' , description: 'A bag to hold bait', price: "/assets/rupee.png 30")
Item.create!(name: 'Mail Bag', image_url: '/assets/mail bag.png' , description: 'A bag to hold mail', price: "/assets/rupee.png 40")
Item.create!(name: 'Simple Flower', image_url: '/assets/simple flower.png' , description: 'A simple flower to help beautify a town', price: "/assets/rupee.png 10")
Item.create!(name: 'Pretty Flower', image_url: '/assets/pretty flower.png' , description: 'A pretty flower to help beautify a town', price: "/assets/rupee.png 20")
Item.create!(name: 'Exotic Flower', image_url: '/assets/exotic flower.png' , description: 'An exotic flower to help beautify a town', price: "/assets/rupee.png 35")
Item.create!(name: 'Windmill', image_url: '/assets/windmill .png' , description: 'A cute decoration to add some flair to a town', price: "/assets/rupee.png 15")
Item.create!(name: 'Bottle', image_url: '/assets/empty bottle.png' , description: 'Used to hold stuff', price: "/assets/rupee.png 50")
Item.create!(name: 'Green Potion', image_url: '/assets/green potion.png' , description: 'Replenishes magic', price: "/assets/rupee.png 25")
Item.create!(name: 'Blue Potion ', image_url: '/assets/blue potion.png' , description: 'Replenishes both health and magic', price: "/assets/rupee.png 45")
Item.create!(name: "Gramma\'s Soup", image_url: '/assets/gramma\'s soup.png' , description: 'Yummy and replenishes heath, magic, and gives a boost', price: "/assets/rupee.png 50")
Item.create!(name: 'Pear', image_url: '/assets/bait pear.png' , description: 'Used to attract seagulls', price: "/assets/rupee.png 15")
Item.create!(name: 'Telescope', image_url: '/assets/telescope.png' , description: 'Used to see far', price: "/assets/rupee.png 60")
Item.create!(name: 'Treasure Map', image_url: '/assets/treasure map.png' , description: 'Location to some treasure', price: "/assets/rupee.png 50")
Item.create!(name: 'A Piece of Triforce Treasure Map', image_url: '/assets/piece of triforce treasure map .png' , description: 'Location to a piece of the triforce', price: "/assets/rupee.png 150")
Item.create!(name: 'Stick', image_url: '/assets/enemy stick weapon.png' , description: 'A stick', price: "/assets/rupee.png 15")
Item.create!(name: 'Bomb', image_url: '/assets/bomb.png' , description: 'Blows stuff up', price: "/assets/rupee.png 20")
Item.create!(name: 'Boomerang', image_url: '/assets/boomerang.png' , description: 'Throw it and watch it come back', price: "/assets/rupee.png 50")
Item.create!(name: 'Grappling Hook', image_url: '/assets/grappling hook .png' , description: 'Throw at enemies and ledges', price: "/assets/rupee.png 75")
Item.create!(name: 'Bow', image_url: '/assets/bow and arrow.png' , description: 'A bow. Needs Arrows not included', price: "/assets/rupee.png 100")
Item.create!(name: 'Bundle of Arrows', image_url: '/assets/quiver with arrows.png' , description: 'Bundle of 10 arrows', price: "/assets/rupee.png 25")
Item.create!(name: 'Hammer', image_url: '/assets/hammer .png' , description: 'Great at hitting giant birds', price: "/assets/rupee.png 200")
Item.create!(name: 'Iron Boots', image_url: '/assets/iron boots.png' , description: 'Makes you an immovable force', price: "/assets/rupee.png 250")
Item.create!(name: 'Deku Leaf', image_url: '/assets/deku leaf .png' , description: 'Creates a powerful gust of wind', price: "/assets/rupee.png 150")
Item.create!(name: "Hero\'s Sword", image_url: '/assets/master sword.png' , description: 'A sword that can seal darkness', price: "/assets/rupee.png 450")
Item.create!(name: "Hero\'s Outfit", image_url: '/assets/hero\'s tunic.png' , description: 'Said to have belonged to a hero from another time', price: "/assets/rupee.png 200")
Item.create!(name: 'Piece of Heart', image_url: '/assets/piece of heart .png' , description: 'Collect 4 to complete a Heart Container', price: "/assets/rupee.png 150")

Review.create!(title: 'Great Purchase!', body: 'Holds all the goods I get from killing enemies',  user_id: 1, item_id: 1)
Review.create!(title: 'Nice', body: 'Perfect storage for my bait',  user_id: 2, item_id: 2)
Review.create!(title: 'Not Bad', body: "Does what it\'s supposed to",  user_id: 3, item_id: 3)
Review.create!(title: 'Okay', body: 'Nothing special, but adds a nice little flair',  user_id: 4, item_id: 4)
Review.create!(title: 'Pretty Nice', body: 'Looks really good',  user_id: 5, item_id: 5)
Review.create!(title: 'Beautiful!', body: 'Love the color and the design!',  user_id: 1, item_id: 6)
Review.create!(title: 'Cute', body: "It\'s a fun little touch to the area",  user_id: 2, item_id: 7)
Review.create!(title: 'Absoulte Necessity!', body: "Can\'t get far without this. Bought 4",  user_id: 3, item_id: 8)
Review.create!(title: 'Helpful', body: 'Nice to have on hand',  user_id: 4, item_id: 9)
Review.create!(title: 'Great Purchase!', body: 'Really great thing to have on hand',  user_id: 5, item_id: 10)
Review.create!(title: 'Tasty and Hearty', body: "Better than any potion I\'ve ever had",  user_id: 1, item_id: 11)
Review.create!(title: 'Not Bad', body: "It\'s alright; does what it needs to, but nothing special",  user_id: 2, item_id: 12)
Review.create!(title: 'Love This!', body: "Love it! I can\'t go anywhere without it",  user_id: 3, item_id: 13)
Review.create!(title: 'Not Easy to Use', body: "The directions aren\'t very clear, but it\'s better than nothing",  user_id: 4, item_id: 14)
Review.create!(title: 'Amazing!', body: 'It led me amazing treasure',  user_id: 5, item_id: 15)
Review.create!(title: 'Okay', body: 'Not bad for a cheap weapon',  user_id: 5, item_id: 16)
Review.create!(title: 'Necessary', body: "Always have some of these on me; they\'re always super useful",  user_id: 1, item_id: 17)
Review.create!(title: 'Difficult to Use', body: 'Pretty good weapon, but takes a lot of practice',  user_id: 2, item_id: 18)
Review.create!(title: 'So Much Fun!', body: 'I love that this has unlocked so many new places for me. AND, it can also be used as a weapon!',  user_id: 3, item_id: 19)
Review.create!(title: 'Good Buy', body: 'Great long-ranged weapon',  user_id: 4, item_id: 20)
Review.create!(title: 'Okay', body: 'Nothing special',  user_id: 5, item_id: 21)
Review.create!(title: 'Heavy but Strong', body: 'Very powerful, but super heavy',  user_id: 1, item_id: 22)
Review.create!(title: 'Great Purchase!', body: "Nothing can push me over when I\'m wearing these. Highly recommend",  user_id: 2, item_id: 23)
Review.create!(title: 'Suprisingly Useful!', body: "Doesn\'t seem like much, but it\'s incredibly handy",  user_id: 3, item_id: 24)
Review.create!(title: 'Legendary', body: "The only sword I\'ll ever need",  user_id: 4, item_id: 25)
Review.create!(title: 'Comfy', body: 'Super comfortable to move around in',  user_id: 5, item_id: 26)
Review.create!(title: 'Great', body: 'Getting 4 of these really made my life easier; wish I only needed one though',  user_id: 1, item_id: 27)




